--(1) 박지성이 구매한 도서의 출판사와 같은 출판사에서 도서를 구매한 고객의 이름:
SELECT
    DISTINCT CUSTOMERS.NAME
FROM
    CUSTOMERS
    JOIN ORDERS
    ON CUSTOMERS.CUSTOMER_ID = ORDERS.CUSTOMER_ID JOIN ORDER_DETAILS
    ON ORDERS.ORDER_ID = ORDER_DETAILS.ORDER_ID
    JOIN BOOKS
    ON ORDER_DETAILS.BOOK_ID = BOOKS.BOOK_ID
WHERE
    BOOKS.PUBLISHER = (
        SELECT
            PUBLISHER
        FROM
            BOOKS
            JOIN ORDER_DETAILS
            ON BOOKS.BOOK_ID = ORDER_DETAILS.BOOK_ID JOIN ORDERS
            ON ORDER_DETAILS.ORDER_ID = ORDERS.ORDER_ID
            JOIN CUSTOMERS
            ON ORDERS.CUSTOMER_ID = CUSTOMERS.CUSTOMER_ID
        WHERE
            CUSTOMERS.NAME = '박지성'
    )
    AND CUSTOMERS.NAME != '박지성';

--(2) 2 개 이상의 서로 다른 출판사에서 도서를 구매한 고객의 이름:
SELECT
    CUSTOMERS.NAME
FROM
    CUSTOMERS
    JOIN ORDERS
    ON CUSTOMERS.CUSTOMER_ID = ORDERS.CUSTOMER_ID JOIN ORDER_DETAILS
    ON ORDERS.ORDER_ID = ORDER_DETAILS.ORDER_ID
    JOIN BOOKS
    ON ORDER_DETAILS.BOOK_ID = BOOKS.BOOK_ID
GROUP BY
    CUSTOMERS.CUSTOMER_ID, CUSTOMERS.NAME
HAVING
    COUNT(DISTINCT BOOKS.PUBLISHER) >= 2;

--(3) 전체 고객의 30% 이상이 구매한 도서:
SELECT
    CUSTOMERS.NAME
FROM
    CUSTOMERS
    JOIN ORDERS
    ON CUSTOMERS.CUSTOMER_ID = ORDERS.CUSTOMER_ID
GROUP BY
    CUSTOMERS.CUSTOMER_ID, CUSTOMERS.NAME
HAVING
    COUNT(DISTINCT ORDERS.ORDER_ID) >= (
        SELECT
            0.3 * COUNT(DISTINCT ORDERS.ORDER_ID)
        FROM
            ORDERS
    );